/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mars_JniUtils */

#ifndef _Included_com_mars_JniUtils
#define _Included_com_mars_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mars_JniUtils
 * Method:    d1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_JniUtils_d1
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mars_JniUtils
 * Method:    e1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_JniUtils_e1
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mars_JniUtils
 * Method:    method1
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_JniUtils_method1
        (JNIEnv *, jclass, jstring);

/*
 * Class:     com_mars_JniUtils
 * Method:    method2
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mars_JniUtils_method2
        (JNIEnv *, jclass, jstring);


#ifdef __cplusplus
}
#endif
#endif
